Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.


In [2]:
# D = np.diag([1, 2, 3])
import numpy as np
# 대각 행렬 정의
D = np.diag([1, 2, 3])

# 대각 행렬의 역행렬
D_inv = np.linalg.inv(D)

# 원래 대각 행렬과 역행렬의 곱
result = np.dot(D, D_inv)

# 소수점 둘째 자리까지 출력
np.set_printoptions(precision=2)

# 결과 출력
print('D = \n', D)
print('D_inv = \n', D_inv)
print('D x D_inv = \n', result)

D = 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
D_inv = 
 [[1.   0.   0.  ]
 [0.   0.5  0.  ]
 [0.   0.   0.33]]
D x D_inv = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [3]:
import numpy as np

# 상삼각 행렬 정의
U = np.triu(np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]]))

# 상삼각 행렬의 전치
U_T = U.T

print("상삼각 행렬 U:")
print(U)

print("상삼각 행렬 U의 전치:")
print(U_T)

상삼각 행렬 U:
[[1 2 3]
 [0 4 5]
 [0 0 6]]
상삼각 행렬 U의 전치:
[[1 0 0]
 [2 4 0]
 [3 5 6]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

In [4]:
# A = np.array([[4, 7], [2, 6]])
import numpy as np

# 행렬 정의
A = np.array([[4, 7], [2, 6]])

# 행렬의 역행렬
A_inv = np.linalg.inv(A)

# 원래 행렬과 역행렬의 곱
result = np.dot(A, A_inv)

# 단위 행렬
I = np.eye(2)

# 소수점 둘째 자리까지 출력
np.set_printoptions(precision=2)

# 결과 출력
print('A = \n', A)
print('A_inv = \n', A_inv)
print('A x A_inv = \n', result)
print('Is A x A_inv equal to I ? ', np.allclose(result, I))

A = 
 [[4 7]
 [2 6]]
A_inv = 
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A x A_inv = 
 [[ 1.00e+00 -1.11e-16]
 [ 1.11e-16  1.00e+00]]
Is A x A_inv equal to I ?  True


Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [5]:
import numpy as np

# 입력 데이터 포인트 (1, x1, x2)
X = np.array([[1, 2, 3]])

# 모델 파라미터 (θ0, θ1, θ2)
theta = np.array([0.5, 1.5, -2.0])

# 선형 회귀 모델의 예측값 계산
y_pred = np.dot(X, theta)

# 결과 출력
print("X = ", X)
print("theta = ", theta)
print("y_pred = ", y_pred)

X =  [[1 2 3]]
theta =  [ 0.5  1.5 -2. ]
y_pred =  [-2.5]


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [8]:
import numpy as np

# 입력 벡터 (x1, x2, x3)
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 (각 행이 뉴런의 가중치를 나타냄)
W = np.array([[0.2, -0.3, 0.5],
              [0.4, 0.1, -0.2],
              [-0.5, 0.4, 0.3]])

# 신경망의 단일 계층 출력 계산
output = np.dot(W, X)

print("Input Vector X =", X)
print(f"Weight Matrix W = \n{W}")
print("Layer Output =", output)

Input Vector X = [ 0.5  1.  -1.5]
Weight Matrix W = 
[[ 0.2 -0.3  0.5]
 [ 0.4  0.1 -0.2]
 [-0.5  0.4  0.3]]
Layer Output = [-0.95  0.6  -0.3 ]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [9]:
# X = np.array([0.5, 1.0, -1.5])
import numpy as np

# 활성화 함수 정의
def relu(x) :
  return np.maximum(0, x)

def sigmoid(x) :
  return 1 / (1 + np.exp(-x))

# 입력 벡터 정의
X = np.array([1, -2, 3])

# 가중치 행렬과 편향 벡터 정의
W = np.array([[0.2, -0.5, 0.3],
              [0.4, 0.1, -0.2],
              [-0.3, 0.4, 0.6]])
b = np.array([0.1, -0.2, 0.3])

# 신경망의 선형 변환 계산
Z = np.dot(W, X) + b

# 활성화 함수 적용
output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print("Input Vector X =", X)
print("Weight Matrix W =\n", W)
print("Bias Vector b=", b)
print("Linear Transformation Z =", Z)
print("Output after ReLU Activation =", output_relu)
print("Output after Sigmoid Activation =", output_sigmoid)

Input Vector X = [ 1 -2  3]
Weight Matrix W =
 [[ 0.2 -0.5  0.3]
 [ 0.4  0.1 -0.2]
 [-0.3  0.4  0.6]]
Bias Vector b= [ 0.1 -0.2  0.3]
Linear Transformation Z = [ 2.2 -0.6  1. ]
Output after ReLU Activation = [2.2 0.  1. ]
Output after Sigmoid Activation = [0.9  0.35 0.73]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [10]:
import numpy as np

# 계수 행렬 A와 결과 벡터 b 정의
A = np.array([[3, 4], [2, 1]])
b = np.array([10, 5])

# 역행렬 계산
A_inv = np.linalg.inv(A)

# 변수 x 계산
x = np.dot(A_inv, b)

print("Coefficient Matrix A =\n", A)
print("Result Vector b =", b)
print("Inverse of Coefficient Matrix A =\n", A_inv)
print("Solution Vector x =", x)

Coefficient Matrix A =
 [[3 4]
 [2 1]]
Result Vector b = [10  5]
Inverse of Coefficient Matrix A =
 [[-0.2  0.8]
 [ 0.4 -0.6]]
Solution Vector x = [2. 1.]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [11]:
import numpy as np

# 원래 점의 좌표 p와 변환 행렬 T 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 새로운 좌표 p 계산
p_prime = np.dot(T, p)

# 변환 행렬 T의 역행렬 계산
T_inv = np.linalg.inv(T)

# 새로운 좌표 p에서 원래 좌표 p를 복원
p_original = np.dot(T_inv, p_prime)

print("Original Point p =", p)
print("Transformation Matrix T =\n", T)
print("Transformed Point p =", p_prime)
print("Inverse of T (T_inv) =\n", T_inv)
print("Original Point p =", p_original)

Original Point p = [1 2]
Transformation Matrix T =
 [[2 0]
 [0 3]]
Transformed Point p = [2 6]
Inverse of T (T_inv) =
 [[0.5  0.  ]
 [0.   0.33]]
Original Point p = [1. 2.]
